export const queryKeys = {
  users: (page: number, limit: number) => ['users', { page, limit }] as const,
  tenants: (filters: object) => ['tenants', filters] as const,
  tenant: (id: string) => ['tenant', id] as const,
  properties: (filters: object) => ['properties', filters] as const,
  property: (id: string) => ['property', id] as const,
  buildings: (filters: object) => ['buildings', filters] as const,
  building: (id: string) => ['building', id] as const,
  contracts: (filters: object) => ['contracts', filters] as const,
  contract: (id: string) => ['contract', id] as const,
  invoices: (filters: object) => ['invoices', filters] as const,
  invoice: (id: string) => ['invoice', id] as const,
  paymentReview: (filters: object) => ['payments', 'review', filters] as const,
  dashboard: ['dashboard'] as const,
  notifications: ['notifications'] as const,
};
